repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: check-merge-conflict
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
        exclude: templates/.+\.ya?ml
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args: [ '--verbose' ]
